### PR TITLE
Finnish translation

### PR DESCRIPTION
**Pull request by Orlandoxx**
for EITConfig plugin.

### CODE REVIEW

**Comment by Huevos** [comment]
1) You also will need to add the .mo. Like you did in SelectRemote. See here:
https://github.com/Huevos/RemoteControlSelection/tree/master/usr/lib/enigma2/python/Plugins/SystemPlugins/RemoteControlSelection/locale/fi/LC_MESSAGES

2) We are going to add a help page so there will be more text soon.

**Comment by Orlandoxx** [comment]
Thanx.

**Comment by Orlandoxx** [comment]
By the way 'SimpleChannelSelection' is causing lot of 'Error in screen'. Can you check the reason for those errors ?

**Comment by Huevos** [comment]
Can you post the log for those problems on the forum please.

**Comment by Huevos** [comment]
No idea what you have done.

I've had to revert it.

https://github.com/Huevos/EITConfig/commit/c9b853c2c943b1adf61714136dabee62761e8daf

**Comment by Orlandoxx** [comment]
I wrote to the forum with debug log.

**Comment by Huevos** [comment]
https://github.com/Huevos/EITConfig/commit/c9b853c2c943b1adf61714136dabee62761e8daf

I have had to revert that.

**Comment by Orlandoxx** [comment]
This link is wrong : https://github.com/Huevos/EITConfig/tree/master/usr/lib/enigma2/python/Plugins/SystemPlugins/RemoteControlSelection/locale/fi/LC_MESSAGES

Should it be : https://github.com/Huevos/EITConfig/tree/master/usr/lib/enigma2/python/Plugins/SystemPlugins/EITConfig/locale/fi/LC_MESSAGES

**Comment by Huevos** [comment]
No.

**Pull request merged**
